A11_RBS/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using A11_RBS.Domain;
using A11_RBS.CustomFilters;

namespace A11_RBS.Controllers
{
    public class VisitorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Visitor/
        public ActionResult Index()
        {
            return View(db.InterviewRegistration.ToList());
        }

        // GET: /Visitor/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitors visitors = db.InterviewRegistration.Find(id);
            if (visitors == null)
            {
                return HttpNotFound();
            }
            return View(visitors);
        }

        // GET: /Visitor/Create
        public ActionResult Create()
        {
            List<string> experience = new List<string>(){
                "Fresher",
                "1-3 Years",
                "3-7 Years",
                "7+ Years"
            };

            ViewBag.Experience = new SelectList(experience);
            List<string> know = new List<string>(){
                "Facebook",
                "Direct Website",
                "Through Employee",
                "Friends"
            };

            ViewBag.KnowaboutUse = new SelectList(know);
            List<string> ExpectedJoin = new List<string>(){
                "Immediate",
                "With in 15 days",
                "With in a month",
                "With in 3 months",
                "More than 3 months"
            };

            ViewBag.ExpectedJoining = new SelectList(ExpectedJoin);
            return View();
        }

        // POST: /Visitor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,FatherName,Email, Phone,Qualification,Stream,Skills,Experience, CurrentCTC, ExpectedJoining, KnowaboutUse")] Visitors visitors)
        {
            if (ModelState.IsValid)
            {
                visitors.Id = Guid.NewGuid();
                db.InterviewRegistration.Add(visitors);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<string> experience = new List<string>(){
                "Fresher",
                "1-3 Years",
                "3-7 Years",
                "7+ Years"
            };

            ViewBag.Experience = new SelectList(experience);
            List<string> know = new List<string>(){
                "Facebook",
                "Direct Website",
                "Through Employee",
                "Friends"
            };

            ViewBag.KnowaboutUse = new SelectList(know);

            List<string> ExpectedJoin = new List<string>(){
                "Immediate",
                "With in 15 days",
                "With in a month",
                "With in 3 months",
                "More than 3 months"
            };

            ViewBag.ExpectedJoining = new SelectList(ExpectedJoin);
            
            return View(visitors);
        }

        // GET: /Visitor/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitors visitors = db.InterviewRegistration.Find(id);
            if (visitors == null)
            {
                return HttpNotFound();
            }
            return View(visitors);
        }

        // POST: /Visitor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,FatherName,Email, Phone,Qualification,Stream,Skills,Experience,CurrentCTC,ExpectedJoining,KnowaboutUse")] Visitors visitors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visitors).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(visitors);
        }

        // GET: /Visitor/Delete/5
        [AuthLog(Roles="Super Admin, Office Manager, Project Manager")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitors visitors = db.InterviewRegistration.Find(id);
            if (visitors == null)
            {
                return HttpNotFound();
            }
            return View(visitors);
        }

        // POST: /Visitor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Visitors visitors = db.InterviewRegistration.Find(id);
            db.InterviewRegistration.Remove(visitors);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

A11_RBS/Views/Visitor/Create.cshtml
@model A11_RBS.Domain.Visitors

@{
    ViewBag.Title = "Create";
}

<style>
    .form-group{
       
    }
    .control-label{
        font-weight:bolder;
        font-size:15px;
    }
    .text-box{
        width:200px;
    }
</style>
<h2 class="btn btn-primary" style="margin-bottom: 20px; margin-left: 270px;">Interview Candidate Registration</h2>


@using (Html.BeginForm("Create","Visitor"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("First Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.FirstName)
                            @Html.ValidationMessageFor(model => model.FirstName)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Last Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.LastName)
                            @Html.ValidationMessageFor(model => model.LastName)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Father Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.FatherName)
                            @Html.ValidationMessageFor(model => model.FatherName)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Phone Number", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Phone)
                            @Html.ValidationMessageFor(model => model.Phone)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Email", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Email)
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Highest Qualification", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Qualification)
                            @Html.ValidationMessageFor(model => model.Qualification)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Stream, new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Stream)
                            @Html.ValidationMessageFor(model => model.Stream)
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Address)
                            @Html.ValidationMessageFor(model => model.Address)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Technical Skills", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Skills)
                            @Html.ValidationMessageFor(model => model.Skills)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Experience", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                                 @Html.DropDownList("Experience", "Choose one")
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Current CTC", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.CurrentCTC)
                            @Html.ValidationMessageFor(model => model.CurrentCTC)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("How soon you can Join", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.DropDownList("ExpectedJoining", "Choose one")
                        </div>
                    </div>
                        
                    <div class="form-group">
                        @Html.Label("How Do You Know About Us", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            <!--
                Html.EnumDropDownListFor(model => model.KnowaboutUse)
                Html.ValidationMessageFor(model => model.KnowaboutUse)-->
                            @Html.DropDownList("KnowaboutUse", "Choose one")
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-7">
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                    </div>
                </div>
        </div>
    </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

A11_RBS/Views/Visitor/Delete.cshtml
@model A11_RBS.Domain.Visitors

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visitors</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stream)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stream)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skills)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skills)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentCTC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentCTC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpectedJoining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpectedJoining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KnowaboutUse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KnowaboutUse)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

A11_RBS/Views/Visitor/Details.cshtml
@model A11_RBS.Domain.Visitors

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Visitors</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stream)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stream)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skills)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skills)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentCTC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentCTC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpectedJoining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpectedJoining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KnowaboutUse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KnowaboutUse)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

A11_RBS/Views/Visitor/Edit.cshtml
@model A11_RBS.Domain.Visitors

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Visitors</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatherName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatherName)
                @Html.ValidationMessageFor(model => model.FatherName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qualification, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qualification)
                @Html.ValidationMessageFor(model => model.Qualification)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stream, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stream)
                @Html.ValidationMessageFor(model => model.Stream)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Skills, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Skills)
                @Html.ValidationMessageFor(model => model.Skills)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience)
                @Html.ValidationMessageFor(model => model.Experience)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentCTC, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentCTC)
                @Html.ValidationMessageFor(model => model.CurrentCTC)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpectedJoining, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpectedJoining)
                @Html.ValidationMessageFor(model => model.ExpectedJoining)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KnowaboutUse, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KnowaboutUse)
                @Html.ValidationMessageFor(model => model.KnowaboutUse)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

A11_RBS/Views/Visitor/Index.cshtml
@model IEnumerable<A11_RBS.Domain.Visitors>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Qualification)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stream)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skills)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Experience)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentCTC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpectedJoining)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Qualification)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stream)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Skills)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Experience)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentCTC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpectedJoining)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>