A11_RBS/Models/LeavesViewModel.cs
using A11_RBS.Domain;
using A11_RBS.Infrastructure.EnumsExtensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace A11_RBS.Models
{
    public class LeavesModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Please Select the Type of Leave")]
        [Display(Name = "Type of Leave")]
        [EnumDataType(typeof(LeaveType))]
        public LeaveType LeaveType { get; set; }

        [Display(Name = "Reason")]
        public string Reason { get; set; }

        [Required(ErrorMessage = "Please tell us how many leaves you are requesting for?")]
        [Range(1, 15, ErrorMessage = "Should be Greater than Zero")]
        [Display(Name = "How Many Leaves?")]
        public int NoOfDays { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString =
           "{0:yyyy-MM-dd}",
            ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Please mention the leave starting Date")]
        [Display(Name = "Starting From or One Day")]
        public DateTime FromDate { get; set; }

        [Display(Name = "Leave Till")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString =
           "{0:yyyy-MM-dd}",
            ApplyFormatInEditMode = true)]
        public DateTime? ToDate { get; set; }

        [Display(Name = "Leave Status")]
        [EnumDataType(typeof(LeaveApprovalStatus))]
        public LeaveApprovalStatus IsApproved { get; set; }
        public string Comments { get; set; } 

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString =
           "{0:yyyy-MM-dd}",
            ApplyFormatInEditMode = true)]
        public DateTime RequestedDateTime { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString =
           "{0:yyyy-MM-dd}",
            ApplyFormatInEditMode = true)]
        public DateTime RespondedDateTime { get; set; }

       

    }
}

A11_RBS/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using A11_RBS.Domain;
using A11_RBS.Infrastructure.Services;
using A11_RBS.CustomFilters;
using A11_RBS.Models;
using A11_RBS.Infrastructure.EnumsExtensions;
using AutoMapper;
using A11_RBS.Infrastructure.Repository;

namespace A11_RBS.Controllers
{
    public class LeaveController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        Repository<ApplicationUser> user = new Repository<ApplicationUser>();
        // GET: /Leave/
        public ActionResult Index()
        {
          
                List<Leaves> use = db.Users.Find(UserExtensions.GetUserId()).LeavesRequests.OrderByDescending(m => m.IsApproved).ToList<Leaves>();
                return View(use);
           
        }

        // GET: /Leave/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leaves leaves = db.Leaves.Find(id);
            if (leaves == null)
            {
                return HttpNotFound();
            }
            return View(leaves);
        }

        // GET: /Leave/Create
        public ActionResult Create()
        {
            return View();
        }


        //
        // POST: /Leave/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LeaveType,Reason,NoOfDays,FromDate,ToDate,Comments")]Leaves leaves)
        {
            if (ModelState.IsValid)
            {
                leaves.Id = Guid.NewGuid();

                leaves.RequestedDateTime = DateTime.Now;
                leaves.IsApproved = LeaveApprovalStatus.Pending;
                ApplicationUser use = db.Users.Find(UserExtensions.GetUserId());
                use.LeavesRequests.Add(leaves);
                db.SaveChanges();



                return RedirectToAction("Index");
            }

            return View(leaves);
        }

        // GET: /Leave/Edit/5
       
        [AuthLog(Roles="Office Manager, Project Manager,Super Admin")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leaves leaves = db.Leaves.Find(id);
            if (leaves == null)
            {
                return HttpNotFound();
            }
            return View();
        }

        // POST: /Leave/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="LeaveType,Reason,NoOfDays,RequestedDateTime,FromDate,ToDate,IsApproved,RespondedDateTime,Comments")]Leaves leaves)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leaves).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(leaves);
        }

        // GET: /Leave/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leaves leaves = db.Leaves.Find(id);
            if (leaves == null)
            {
                return HttpNotFound();
            }
            return View(leaves);
        }

        // POST: /Leave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Leaves leaves = db.Leaves.Find(id);
            db.Leaves.Remove(leaves);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



          [AuthLog(Roles="Super Admin, Office Manager, Project Manager")]  
        public ActionResult LeaveRequests()
        {
            string id = UserExtensions.GetUserId();
            List<ApplicationUser> LeavesForApproval = user.Get(filter: m => m.Id != id, includeProperties: "LeavesRequests").ToList<ApplicationUser>();


            List<Leaves> use =new List<Leaves>();
            foreach (var m in LeavesForApproval)
            {
                foreach (var l in m.LeavesRequests)
                {
                    if (l.IsApproved == LeaveApprovalStatus.Pending)
                    {
                        use.Add(l);
                    }
                }
            }
                return View(use);
            
        }


            [HttpPost]
          public ActionResult LeaveRequests(IList<Leaves> LeaveApprovals)
          {
              if (ModelState.IsValid)
              {
                  foreach (Leaves b in LeaveApprovals)
                  {
                      
                      db.Entry(b).State = EntityState.Modified;
                  }
                  db.SaveChanges();
                  return View("Index", "Home");
              }
              else
              {
                  return View();
              }
          }


        
             public ActionResult LeaveApproved(Guid Id)
            {
                if (Id != null )
                {
                    Leaves l = db.Leaves.Find(Id);
                    l.IsApproved = LeaveApprovalStatus.Approved;
                    db.SaveChanges();
                    return RedirectToAction("LeaveRequests");
                }
                return View();
          }

          public ActionResult LeaveNotApproved(Guid Id)
            {
                if (Id != null )
                {
                    Leaves l = db.Leaves.Find(Id);
                    l.IsApproved = LeaveApprovalStatus.NotApproved;
                    db.SaveChanges();
                    return RedirectToAction("LeaveRequests");
                }
                return View();
          }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

A11_RBS/Controllers/LeavesController.cs
using A11_RBS.Domain;
using A11_RBS.Infrastructure.EnumsExtensions;
using A11_RBS.Infrastructure.Repository;
using A11_RBS.Infrastructure.Services;
using A11_RBS.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace A11_RBS.Controllers
{
    public class LeavesController : Controller
    {
        //
        // GET: /Leaves/

        

        
        Repository<ApplicationUser> apprepo = new Repository<ApplicationUser>();

        public ActionResult Index()
        {
            string userId = UserExtensions.GetUserId();
            IList<Leaves> PreviousLeaves = apprepo.GetById(UserExtensions.GetUserId()).LeavesRequests.ToList<Leaves>();

            return View(PreviousLeaves);
        }

        public ActionResult ApplyForLeave()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ApplyForLeave([Bind(Exclude = ("ApprovedBy,RequestedDateTime,RespondedDateTime,IsApproved,Comments"))]Leaves model)
        {

            if (ModelState.IsValid)
            {

                ApplicationUser use = apprepo.GetById(UserExtensions.GetUserId());
                use.LeavesRequests.Add(model);
                apprepo.Edit(use);
               


                return RedirectToAction("Index", "Leaves");
            }

            return View(model);
        }




    }
}

A11_RBS/Views/Leave/Create.cshtml
@model A11_RBS.Models.LeavesModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Leave",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.LeaveType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.LeaveType)
                @Html.ValidationMessageFor(model => model.LeaveType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reason, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reason)
                @Html.ValidationMessageFor(model => model.Reason)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfDays, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfDays)
                @Html.ValidationMessageFor(model => model.NoOfDays)
            </div>
        </div>
           
        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate)
                @Html.ValidationMessageFor(model => model.FromDate)
            </div>
        </div>

            
        <div class="form-group">
            @Html.LabelFor(model => model.ToDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDate)
                @Html.ValidationMessageFor(model => model.ToDate)
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.Comments, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments)
                @Html.ValidationMessageFor(model => model.Comments)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

A11_RBS/Views/Leave/Delete.cshtml
@model A11_RBS.Domain.Leaves

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leaves</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

A11_RBS/Views/Leave/Details.cshtml
@model A11_RBS.Models.LeavesModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Leaves</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

A11_RBS/Views/Leave/Edit.cshtml
@model A11_RBS.Models.LeavesModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leaves</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LeaveType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.LeaveType)
                @Html.ValidationMessageFor(model => model.LeaveType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reason, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reason)
                @Html.ValidationMessageFor(model => model.Reason)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfDays, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfDays)
                @Html.ValidationMessageFor(model => model.NoOfDays)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate)
                @Html.ValidationMessageFor(model => model.FromDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDate)
                @Html.ValidationMessageFor(model => model.ToDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.IsApproved)
                @Html.ValidationMessageFor(model => model.IsApproved)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments)
                @Html.ValidationMessageFor(model => model.Comments)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

A11_RBS/Views/Leave/Index.cshtml
@model IEnumerable<A11_RBS.Domain.Leaves>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LeaveType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reason)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfDays)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApproved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LeaveType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Reason)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoOfDays)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

A11_RBS/Views/Leave/LeaveRequests.cshtml
@model IEnumerable<A11_RBS.Domain.Leaves>

@{
    ViewBag.Title = "LeaveRequests";
}

<h2 class="btn btn-primary btn-lg disabled">Pending For Approval</h2>

<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LeaveType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reason)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfDays)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RequestedDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApproved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.Label("Respond")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reason)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequestedDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FromDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsApproved)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td> 
                <a href="/Leave/LeaveApproved?Id=@item.Id">Approved</a> | <a href="/Leave/LeaveNotApproved?Id=@item.Id">NotApproved</a>
            </td>
        </tr>
    }

</table>